[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
]
resolver = "2"

[profile.release]
opt-level = "z"
panic = "abort"
lto = "thin"
debug = 0
incremental = false
codegen-units = 1
strip = "symbols"
